{
 "title": "AWS Infrastructure - PRD",
 "description": "Visualize estimated AWS charges per AWS resource (EC2, S3, ...)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CloudWatch Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CloudWatch" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Alarms - ALARM" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Instances Running EC2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Running Total Instances" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Serviços em uso na AWS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "ELB Application" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "ELB Classic" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Running Instances" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "EC2" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Volumes EBS" ],
       "text": "setAlias(Volumes EBS)"
      }
     ],
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Volumes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Lambda" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Lambda" ],
       "text": "setAlias(Lambda)"
      }
     ],
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Funçoes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "S3" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Buckets S3" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Cluster RDS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SNS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Topics SNS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Fila SQS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "ElastiCache" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Cluster Redis" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Quantidade Elastic IP" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Instances Running On demand EC2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Running Instances Ondemand" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Running Instances EC2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "application": { "filter": "EC2" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Running Total Instances" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "application": { "filter": "EC2" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Running Instances Ondemand" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "application": { "filter": "EC2" },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Running Instances Spot" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Instances Running Spot EC2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Running Instances Spot" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Instances Stopped EC2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Stopped instances" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IAM Users",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "IAM" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Quantidade Users" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Buckets S3",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Buckets S3" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lambdas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Funçoes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EBS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Volumes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EBS unencrypted",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Volumes nao Encriptados" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ELB Application",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "ELB Application" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cluster RDS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Cluster RDS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Topics SNS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SNS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Topics SNS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cluster Redis",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ElastiCache" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Cluster Redis" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Elastic IP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Quantidade Elastic IP" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Snapshots" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cluster ECS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ECS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Cluster ECS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "S3 unencrypted",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Buckets S3 Sem Criptografia" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lambdas - 180d",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": {
      "filter": "Qtd. Lambdas sem invocation nos ultimos 180 dias"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EBS available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Volumes Available" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ELB Classic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "ELB Classic" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RDS instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Instances RDS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Fila SQS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Fila SQS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ElastiCache" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Nó Redis" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Elastic IP available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Quantidade Elastic IP Sem Uso" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AMIs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "AMIs" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Task Definition",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ECS" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Task Definition Name" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bucket Público",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Quantidade Buckets S3 Publicos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lambdas - 90d",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": {
      "filter": "Qtd. Lambdas sem invocation nos ultimos 90 dias"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Panel Title", "type": "mxswat-separator-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Itens sem TAG \"Tribo\" ou com valor \"ALevantar\"",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "EC2 instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Instancias Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Buckets S3",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Buckets S3 Sem Tag" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lambdas",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Lambas Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EBS",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "EBS Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ELB Application",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "ELB Application Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Topics SNS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "SNS Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis node",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Nó Redis Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Elastic IP",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "ElasticIp Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ELB Classic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "ELB Classic Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Fila SQS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "SQS Sem TAG" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Panel Title", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Quantidade deploy por dia - AWS PRD",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CodeDeploy" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Deploy Succeeded" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CodeDeploy" },
     "group": { "filter": "aws" },
     "host": { "filter": "aws.prd" },
     "item": { "filter": "Deploy Failed" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}